
===========================

log level: 0; error type: no error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
error_on_demand() BOOST_MESSAGE
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: no error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
error_on_demand() BOOST_MESSAGE
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: no error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
error_on_demand() BOOST_MESSAGE
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: no error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
error_on_demand() BOOST_MESSAGE
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: user error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function": error_on_demand() BOOST_ERROR
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: user error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test": error_on_demand() BOOST_ERROR
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: user error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function_param": error_on_demand() BOOST_ERROR
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: user error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test_param": error_on_demand() BOOST_ERROR
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: cpp exception; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: cpp exception; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type:  system error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
Exception in "bad_function": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type:  system error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
Exception in "bad_test::test": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type:  system error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
Exception in "bad_function_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type:  system error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
Exception in "bad_test::test_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: fatal user error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: fatal user error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: fatal system error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
Exception in "bad_function": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function": testing aborted
Leaving  test case "bad_function"
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: fatal system error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
Exception in "bad_test::test": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test": testing aborted
Leaving  test case "bad_test::test"
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
Exception in "bad_function_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function_param": testing aborted
Leaving  test case "bad_function_param"
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted
Leaving  test case "Errors handling test"

===========================

log level: 0; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
Exception in "bad_test::test_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test_param": testing aborted
Leaving  test case "bad_test::test_param"
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: no error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
error_on_demand() BOOST_MESSAGE
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: no error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
error_on_demand() BOOST_MESSAGE
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: no error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
error_on_demand() BOOST_MESSAGE
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: no error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
error_on_demand() BOOST_MESSAGE
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: user error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function": error_on_demand() BOOST_ERROR
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: user error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test": error_on_demand() BOOST_ERROR
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: user error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function_param": error_on_demand() BOOST_ERROR
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: user error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test_param": error_on_demand() BOOST_ERROR
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: cpp exception; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: cpp exception; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type:  system error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
Exception in "bad_function": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type:  system error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
Exception in "bad_test::test": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type:  system error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
Exception in "bad_function_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type:  system error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
Exception in "bad_test::test_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: fatal user error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR
Leaving  test case "bad_function"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: fatal user error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR
Leaving  test case "bad_test::test"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR
Leaving  test case "bad_function_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR
Leaving  test case "bad_test::test_param"
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: fatal system error; test case type: free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function"
(free function)
Exception in "bad_function": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function": testing aborted
Leaving  test case "bad_function"
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: fatal system error; test case type: user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test"
(user test case)
Exception in "bad_test::test": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test": testing aborted
Leaving  test case "bad_test::test"
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_function_param"
(parameterized free function)
Exception in "bad_function_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function_param": testing aborted
Leaving  test case "bad_function_param"
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted
Leaving  test case "Errors handling test"

===========================

log level: 1; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...

Entering test case "Errors handling test"

Entering test case "bad_test::test_param"
(parameterized user test case)
Exception in "bad_test::test_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test_param": testing aborted
Leaving  test case "bad_test::test_param"
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted
Leaving  test case "Errors handling test"

===========================

log level: 2; error type: no error; test case type: free function;
Running 1 test case...
(free function)
error_on_demand() BOOST_MESSAGE

===========================

log level: 2; error type: no error; test case type: user test case;
Running 1 test case...
(user test case)
error_on_demand() BOOST_MESSAGE

===========================

log level: 2; error type: no error; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
error_on_demand() BOOST_MESSAGE

===========================

log level: 2; error type: no error; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
error_on_demand() BOOST_MESSAGE

===========================

log level: 2; error type: user error; test case type: free function;
Running 1 test case...
(free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function": error_on_demand() BOOST_ERROR

===========================

log level: 2; error type: user error; test case type: user test case;
Running 1 test case...
(user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test": error_on_demand() BOOST_ERROR

===========================

log level: 2; error type: user error; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function_param": error_on_demand() BOOST_ERROR

===========================

log level: 2; error type: user error; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test_param": error_on_demand() BOOST_ERROR

===========================

log level: 2; error type: cpp exception; test case type: free function;
Running 1 test case...
(free function)
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 2; error type: cpp exception; test case type: user test case;
Running 1 test case...
(user test case)
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 2; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 2; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 2; error type:  system error; test case type: free function;
Running 1 test case...
(free function)
Exception in "bad_function": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 2; error type:  system error; test case type: user test case;
Running 1 test case...
(user test case)
Exception in "bad_test::test": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 2; error type:  system error; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
Exception in "bad_function_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 2; error type:  system error; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
Exception in "bad_test::test_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 2; error type: fatal user error; test case type: free function;
Running 1 test case...
(free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 2; error type: fatal user error; test case type: user test case;
Running 1 test case...
(user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 2; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 2; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 2; error type: fatal system error; test case type: free function;
Running 1 test case...
(free function)
Exception in "bad_function": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 2; error type: fatal system error; test case type: user test case;
Running 1 test case...
(user test case)
Exception in "bad_test::test": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 2; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
Exception in "bad_function_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 2; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
Exception in "bad_test::test_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 3; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 3; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 3; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 3; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 3; error type: user error; test case type: free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function": error_on_demand() BOOST_ERROR

===========================

log level: 3; error type: user error; test case type: user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test": error_on_demand() BOOST_ERROR

===========================

log level: 3; error type: user error; test case type: parameterized free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function_param": error_on_demand() BOOST_ERROR

===========================

log level: 3; error type: user error; test case type: parameterized user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test_param": error_on_demand() BOOST_ERROR

===========================

log level: 3; error type: cpp exception; test case type: free function;
Running 1 test case...
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 3; error type: cpp exception; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 3; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 3; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 3; error type:  system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 3; error type:  system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 3; error type:  system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 3; error type:  system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 3; error type: fatal user error; test case type: free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 3; error type: fatal user error; test case type: user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 3; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 3; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 3; error type: fatal system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 3; error type: fatal system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 3; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 3; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 4; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 4; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 4; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 4; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 4; error type: user error; test case type: free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function": error_on_demand() BOOST_ERROR

===========================

log level: 4; error type: user error; test case type: user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test": error_on_demand() BOOST_ERROR

===========================

log level: 4; error type: user error; test case type: parameterized free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_function_param": error_on_demand() BOOST_ERROR

===========================

log level: 4; error type: user error; test case type: parameterized user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(44) : error in "bad_test::test_param": error_on_demand() BOOST_ERROR

===========================

log level: 4; error type: cpp exception; test case type: free function;
Running 1 test case...
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 4; error type: cpp exception; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 4; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 4; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 4; error type:  system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 4; error type:  system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 4; error type:  system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 4; error type:  system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 4; error type: fatal user error; test case type: free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 4; error type: fatal user error; test case type: user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 4; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 4; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 4; error type: fatal system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 4; error type: fatal system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 4; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 4; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 5; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 5; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 5; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 5; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 5; error type: user error; test case type: free function;
Running 1 test case...

===========================

log level: 5; error type: user error; test case type: user test case;
Running 1 test case...

===========================

log level: 5; error type: user error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 5; error type: user error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 5; error type: cpp exception; test case type: free function;
Running 1 test case...
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 5; error type: cpp exception; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 5; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 5; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
e:\source code\boost\libs\test\test\errors_handling_test.cpp(55) : last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 5; error type:  system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 5; error type:  system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 5; error type:  system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 5; error type:  system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 5; error type: fatal user error; test case type: free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 5; error type: fatal user error; test case type: user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 5; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 5; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 5; error type: fatal system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 5; error type: fatal system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 5; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 5; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 6; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 6; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 6; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 6; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 6; error type: user error; test case type: free function;
Running 1 test case...

===========================

log level: 6; error type: user error; test case type: user test case;
Running 1 test case...

===========================

log level: 6; error type: user error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 6; error type: user error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 6; error type: cpp exception; test case type: free function;
Running 1 test case...

===========================

log level: 6; error type: cpp exception; test case type: user test case;
Running 1 test case...

===========================

log level: 6; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 6; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 6; error type:  system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 6; error type:  system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 6; error type:  system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 6; error type:  system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": integer divide by zero
e:\source code\boost\libs\test\test\errors_handling_test.cpp(60) : last checkpoint: error_on_demand() divide by zero

===========================

log level: 6; error type: fatal user error; test case type: free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 6; error type: fatal user error; test case type: user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 6; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 6; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 6; error type: fatal system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 6; error type: fatal system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 6; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 6; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 7; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 7; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 7; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 7; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 7; error type: user error; test case type: free function;
Running 1 test case...

===========================

log level: 7; error type: user error; test case type: user test case;
Running 1 test case...

===========================

log level: 7; error type: user error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 7; error type: user error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 7; error type: cpp exception; test case type: free function;
Running 1 test case...

===========================

log level: 7; error type: cpp exception; test case type: user test case;
Running 1 test case...

===========================

log level: 7; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 7; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 7; error type:  system error; test case type: free function;
Running 1 test case...

===========================

log level: 7; error type:  system error; test case type: user test case;
Running 1 test case...

===========================

log level: 7; error type:  system error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 7; error type:  system error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 7; error type: fatal user error; test case type: free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 7; error type: fatal user error; test case type: user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 7; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 7; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
e:\source code\boost\libs\test\test\errors_handling_test.cpp(49) : fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 7; error type: fatal system error; test case type: free function;
Running 1 test case...
Exception in "bad_function": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 7; error type: fatal system error; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 7; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_function_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 7; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": memory access violation
e:\source code\boost\libs\test\test\errors_handling_test.cpp(65) : last checkpoint: error_on_demand() write to an invalid address
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "bad_test::test_param": testing aborted
e:\source code\boost\libs\test\src\unit_test_suite.cpp(87) : fatal error in "Errors handling test": testing aborted

===========================

log level: 8; error type: no error; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: no error; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: no error; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: no error; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: user error; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: user error; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: user error; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: user error; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: cpp exception; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: cpp exception; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type:  system error; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type:  system error; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type:  system error; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type:  system error; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal user error; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal user error; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal system error; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal system error; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal system error; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal system error; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 9; error type: no error; test case type: free function;

===========================

log level: 9; error type: no error; test case type: user test case;

===========================

log level: 9; error type: no error; test case type: parameterized free function;

===========================

log level: 9; error type: no error; test case type: parameterized user test case;

===========================

log level: 9; error type: user error; test case type: free function;

===========================

log level: 9; error type: user error; test case type: user test case;

===========================

log level: 9; error type: user error; test case type: parameterized free function;

===========================

log level: 9; error type: user error; test case type: parameterized user test case;

===========================

log level: 9; error type: cpp exception; test case type: free function;

===========================

log level: 9; error type: cpp exception; test case type: user test case;

===========================

log level: 9; error type: cpp exception; test case type: parameterized free function;

===========================

log level: 9; error type: cpp exception; test case type: parameterized user test case;

===========================

log level: 9; error type:  system error; test case type: free function;

===========================

log level: 9; error type:  system error; test case type: user test case;

===========================

log level: 9; error type:  system error; test case type: parameterized free function;

===========================

log level: 9; error type:  system error; test case type: parameterized user test case;

===========================

log level: 9; error type: fatal user error; test case type: free function;

===========================

log level: 9; error type: fatal user error; test case type: user test case;

===========================

log level: 9; error type: fatal user error; test case type: parameterized free function;

===========================

log level: 9; error type: fatal user error; test case type: parameterized user test case;

===========================

log level: 9; error type: fatal system error; test case type: free function;

===========================

log level: 9; error type: fatal system error; test case type: user test case;

===========================

log level: 9; error type: fatal system error; test case type: parameterized free function;

===========================

log level: 9; error type: fatal system error; test case type: parameterized user test case;

Test suite "call_test_main" failed with:
120 test cases out of 240 passed
120 test cases out of 240 failed
 0 assertions out of 80 passed
80 assertions out of 80 failed
while 80 failures expected
