
===========================

log level: 0; error type: no error; test case type: free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function"
(free function)
error_on_demand() BOOST_MESSAGE
Leaving test case "bad_function"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: no error; test case type: user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test"
(user test case)
error_on_demand() BOOST_MESSAGE
Leaving test case "bad_test::test"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: no error; test case type: parameterized free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function_param"
(parameterized free function)
error_on_demand() BOOST_MESSAGE
Leaving test case "bad_function_param"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: no error; test case type: parameterized user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test_param"
(parameterized user test case)
error_on_demand() BOOST_MESSAGE
Leaving test case "bad_test::test_param"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: user error; test case type: free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function"
(free function)
68: error in "bad_function": error_on_demand() BOOST_ERROR
Leaving test case "bad_function"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: user error; test case type: user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test"
(user test case)
68: error in "bad_test::test": error_on_demand() BOOST_ERROR
Leaving test case "bad_test::test"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: user error; test case type: parameterized free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function_param"
(parameterized free function)
68: error in "bad_function_param": error_on_demand() BOOST_ERROR
Leaving test case "bad_function_param"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: user error; test case type: parameterized user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test_param"
(parameterized user test case)
68: error in "bad_test::test_param": error_on_demand() BOOST_ERROR
Leaving test case "bad_test::test_param"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: cpp exception; test case type: free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function"
(free function)
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error
Leaving test case "bad_function"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: cpp exception; test case type: user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test"
(user test case)
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error
Leaving test case "bad_test::test"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function_param"
(parameterized free function)
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error
Leaving test case "bad_function_param"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test_param"
(parameterized user test case)
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error
Leaving test case "bad_test::test_param"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: fatal user error; test case type: free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function"
(free function)
73: fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR
Leaving test case "bad_function"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: fatal user error; test case type: user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test"
(user test case)
73: fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR
Leaving test case "bad_test::test"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function_param"
(parameterized free function)
73: fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR
Leaving test case "bad_function_param"
Leaving test suite "Errors handling test"

===========================

log level: 0; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test_param"
(parameterized user test case)
73: fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR
Leaving test case "bad_test::test_param"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: no error; test case type: free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function"
(free function)
error_on_demand() BOOST_MESSAGE
Leaving test case "bad_function"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: no error; test case type: user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test"
(user test case)
error_on_demand() BOOST_MESSAGE
Leaving test case "bad_test::test"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: no error; test case type: parameterized free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function_param"
(parameterized free function)
error_on_demand() BOOST_MESSAGE
Leaving test case "bad_function_param"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: no error; test case type: parameterized user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test_param"
(parameterized user test case)
error_on_demand() BOOST_MESSAGE
Leaving test case "bad_test::test_param"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: user error; test case type: free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function"
(free function)
68: error in "bad_function": error_on_demand() BOOST_ERROR
Leaving test case "bad_function"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: user error; test case type: user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test"
(user test case)
68: error in "bad_test::test": error_on_demand() BOOST_ERROR
Leaving test case "bad_test::test"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: user error; test case type: parameterized free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function_param"
(parameterized free function)
68: error in "bad_function_param": error_on_demand() BOOST_ERROR
Leaving test case "bad_function_param"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: user error; test case type: parameterized user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test_param"
(parameterized user test case)
68: error in "bad_test::test_param": error_on_demand() BOOST_ERROR
Leaving test case "bad_test::test_param"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: cpp exception; test case type: free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function"
(free function)
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error
Leaving test case "bad_function"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: cpp exception; test case type: user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test"
(user test case)
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error
Leaving test case "bad_test::test"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function_param"
(parameterized free function)
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error
Leaving test case "bad_function_param"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test_param"
(parameterized user test case)
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error
Leaving test case "bad_test::test_param"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: fatal user error; test case type: free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function"
(free function)
73: fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR
Leaving test case "bad_function"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: fatal user error; test case type: user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test"
(user test case)
73: fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR
Leaving test case "bad_test::test"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_function_param"
(parameterized free function)
73: fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR
Leaving test case "bad_function_param"
Leaving test suite "Errors handling test"

===========================

log level: 1; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
Entering test suite "Errors handling test"
Entering test case "bad_test::test_param"
(parameterized user test case)
73: fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR
Leaving test case "bad_test::test_param"
Leaving test suite "Errors handling test"

===========================

log level: 2; error type: no error; test case type: free function;
Running 1 test case...
(free function)
error_on_demand() BOOST_MESSAGE

===========================

log level: 2; error type: no error; test case type: user test case;
Running 1 test case...
(user test case)
error_on_demand() BOOST_MESSAGE

===========================

log level: 2; error type: no error; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
error_on_demand() BOOST_MESSAGE

===========================

log level: 2; error type: no error; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
error_on_demand() BOOST_MESSAGE

===========================

log level: 2; error type: user error; test case type: free function;
Running 1 test case...
(free function)
68: error in "bad_function": error_on_demand() BOOST_ERROR

===========================

log level: 2; error type: user error; test case type: user test case;
Running 1 test case...
(user test case)
68: error in "bad_test::test": error_on_demand() BOOST_ERROR

===========================

log level: 2; error type: user error; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
68: error in "bad_function_param": error_on_demand() BOOST_ERROR

===========================

log level: 2; error type: user error; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
68: error in "bad_test::test_param": error_on_demand() BOOST_ERROR

===========================

log level: 2; error type: cpp exception; test case type: free function;
Running 1 test case...
(free function)
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 2; error type: cpp exception; test case type: user test case;
Running 1 test case...
(user test case)
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 2; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 2; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 2; error type: fatal user error; test case type: free function;
Running 1 test case...
(free function)
73: fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 2; error type: fatal user error; test case type: user test case;
Running 1 test case...
(user test case)
73: fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 2; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
(parameterized free function)
73: fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 2; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
(parameterized user test case)
73: fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 3; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 3; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 3; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 3; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 3; error type: user error; test case type: free function;
Running 1 test case...
68: error in "bad_function": error_on_demand() BOOST_ERROR

===========================

log level: 3; error type: user error; test case type: user test case;
Running 1 test case...
68: error in "bad_test::test": error_on_demand() BOOST_ERROR

===========================

log level: 3; error type: user error; test case type: parameterized free function;
Running 1 test case...
68: error in "bad_function_param": error_on_demand() BOOST_ERROR

===========================

log level: 3; error type: user error; test case type: parameterized user test case;
Running 1 test case...
68: error in "bad_test::test_param": error_on_demand() BOOST_ERROR

===========================

log level: 3; error type: cpp exception; test case type: free function;
Running 1 test case...
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 3; error type: cpp exception; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 3; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 3; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 3; error type: fatal user error; test case type: free function;
Running 1 test case...
73: fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 3; error type: fatal user error; test case type: user test case;
Running 1 test case...
73: fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 3; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
73: fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 3; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
73: fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 4; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 4; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 4; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 4; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 4; error type: user error; test case type: free function;
Running 1 test case...
68: error in "bad_function": error_on_demand() BOOST_ERROR

===========================

log level: 4; error type: user error; test case type: user test case;
Running 1 test case...
68: error in "bad_test::test": error_on_demand() BOOST_ERROR

===========================

log level: 4; error type: user error; test case type: parameterized free function;
Running 1 test case...
68: error in "bad_function_param": error_on_demand() BOOST_ERROR

===========================

log level: 4; error type: user error; test case type: parameterized user test case;
Running 1 test case...
68: error in "bad_test::test_param": error_on_demand() BOOST_ERROR

===========================

log level: 4; error type: cpp exception; test case type: free function;
Running 1 test case...
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 4; error type: cpp exception; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 4; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 4; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 4; error type: fatal user error; test case type: free function;
Running 1 test case...
73: fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 4; error type: fatal user error; test case type: user test case;
Running 1 test case...
73: fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 4; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
73: fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 4; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
73: fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 5; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 5; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 5; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 5; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 5; error type: user error; test case type: free function;
Running 1 test case...

===========================

log level: 5; error type: user error; test case type: user test case;
Running 1 test case...

===========================

log level: 5; error type: user error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 5; error type: user error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 5; error type: cpp exception; test case type: free function;
Running 1 test case...
Exception in "bad_function": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 5; error type: cpp exception; test case type: user test case;
Running 1 test case...
Exception in "bad_test::test": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 5; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...
Exception in "bad_function_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 5; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...
Exception in "bad_test::test_param": std::runtime_error: test std::runtime error what() message
79: last checkpoint: error_on_demand() throw runtime_error

===========================

log level: 5; error type: fatal user error; test case type: free function;
Running 1 test case...
73: fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 5; error type: fatal user error; test case type: user test case;
Running 1 test case...
73: fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 5; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
73: fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 5; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
73: fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 6; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 6; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 6; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 6; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 6; error type: user error; test case type: free function;
Running 1 test case...

===========================

log level: 6; error type: user error; test case type: user test case;
Running 1 test case...

===========================

log level: 6; error type: user error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 6; error type: user error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 6; error type: cpp exception; test case type: free function;
Running 1 test case...

===========================

log level: 6; error type: cpp exception; test case type: user test case;
Running 1 test case...

===========================

log level: 6; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 6; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 6; error type: fatal user error; test case type: free function;
Running 1 test case...
73: fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 6; error type: fatal user error; test case type: user test case;
Running 1 test case...
73: fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 6; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
73: fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 6; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
73: fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 7; error type: no error; test case type: free function;
Running 1 test case...

===========================

log level: 7; error type: no error; test case type: user test case;
Running 1 test case...

===========================

log level: 7; error type: no error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 7; error type: no error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 7; error type: user error; test case type: free function;
Running 1 test case...

===========================

log level: 7; error type: user error; test case type: user test case;
Running 1 test case...

===========================

log level: 7; error type: user error; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 7; error type: user error; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 7; error type: cpp exception; test case type: free function;
Running 1 test case...

===========================

log level: 7; error type: cpp exception; test case type: user test case;
Running 1 test case...

===========================

log level: 7; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...

===========================

log level: 7; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...

===========================

log level: 7; error type: fatal user error; test case type: free function;
Running 1 test case...
73: fatal error in "bad_function": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 7; error type: fatal user error; test case type: user test case;
Running 1 test case...
73: fatal error in "bad_test::test": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 7; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...
73: fatal error in "bad_function_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 7; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...
73: fatal error in "bad_test::test_param": error_on_demand() BOOST_CRITICAL_ERROR

===========================

log level: 8; error type: no error; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: no error; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: no error; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: no error; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: user error; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: user error; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: user error; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: user error; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: cpp exception; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: cpp exception; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: cpp exception; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: cpp exception; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal user error; test case type: free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal user error; test case type: user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal user error; test case type: parameterized free function;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 8; error type: fatal user error; test case type: parameterized user test case;
Running 1 test case...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

===========================

log level: 9; error type: no error; test case type: free function;

===========================

log level: 9; error type: no error; test case type: user test case;

===========================

log level: 9; error type: no error; test case type: parameterized free function;

===========================

log level: 9; error type: no error; test case type: parameterized user test case;

===========================

log level: 9; error type: user error; test case type: free function;

===========================

log level: 9; error type: user error; test case type: user test case;

===========================

log level: 9; error type: user error; test case type: parameterized free function;

===========================

log level: 9; error type: user error; test case type: parameterized user test case;

===========================

log level: 9; error type: cpp exception; test case type: free function;

===========================

log level: 9; error type: cpp exception; test case type: user test case;

===========================

log level: 9; error type: cpp exception; test case type: parameterized free function;

===========================

log level: 9; error type: cpp exception; test case type: parameterized user test case;

===========================

log level: 9; error type: fatal user error; test case type: free function;

===========================

log level: 9; error type: fatal user error; test case type: user test case;

===========================

log level: 9; error type: fatal user error; test case type: parameterized free function;

===========================

log level: 9; error type: fatal user error; test case type: parameterized user test case;

Test case "call_test_main" passed with:
160 assertions out of 160 passed
  0 assertions out of 160 failed
